using UnityEngine;

namespace FingerPaint
{
    /// <summary>
    /// Plays back a recorded hand animation clip on an XR Hands prefab.
    ///
    /// Setup:
    ///   1. Add an empty GameObject -> HandAnimationPlayer component.
    ///   2. Assign the hand prefab (Left or Right Hand Tracking prefab).
    ///   3. Assign the AnimatorController generated by HandAnimationRecorder.
    ///   4. Press Play — the hand replays the recorded motion.
    ///
    /// How it works:
    ///   - Instantiates the hand prefab as a child.
    ///   - Disables XR tracking components (XRHandSkeletonDriver, XRHandTrackingEvents,
    ///     XRHandMeshController) so they don't fight with the Animator.
    ///   - Adds an Animator component with the recorded controller.
    ///   - The Animator drives the bone transforms instead of live XR tracking.
    /// </summary>
    public class HandAnimationPlayer : MonoBehaviour
    {
        [Header("Hand Prefab")]
        [Tooltip("XR Hands prefab (Left or Right Hand Tracking) — same one used during recording.")]
        [SerializeField] private GameObject _handPrefab;

        [Header("Animation")]
        [Tooltip("AnimatorController generated by HandAnimationRecorder (the .controller file).")]
        [SerializeField] private RuntimeAnimatorController _animatorController;

        [Tooltip("Loop the animation playback.")]
        [SerializeField] private bool _loop = true;

        [Tooltip("Seconds to blend from end pose back to start pose when looping. 0 = hard snap.")]
        [SerializeField] [Range(0f, 2f)] private float _loopBlendDuration = 0.5f;

        [Header("Material Override")]
        [Tooltip("Optional material to apply to the hand mesh. Leave null for the prefab default.")]
        [SerializeField] private Material _handMaterial;

        // ─── Runtime state ──────────────────────────────────────────────

        private GameObject _handInstance;
        private Animator _animator;
        private Vector3 _startLocalPos;
        private Quaternion _startLocalRot;

        // ─── Public API ─────────────────────────────────────────────────

        /// <summary>
        /// Swap the AnimatorController at runtime to play a different recording.
        /// </summary>
        public void SetAnimatorController(RuntimeAnimatorController controller)
        {
            _animatorController = controller;
            if (_animator != null)
                _animator.runtimeAnimatorController = controller;
        }

        /// <summary>
        /// Restart playback from the beginning.
        /// </summary>
        public void Restart()
        {
            if (_animator != null)
                _animator.Play(_animator.GetCurrentAnimatorStateInfo(0).shortNameHash, 0, 0f);
        }

        /// <summary>
        /// Pause or resume playback.
        /// </summary>
        public void SetPaused(bool paused)
        {
            if (_animator != null)
                _animator.speed = paused ? 0f : 1f;
        }

        // ─── Lifecycle ──────────────────────────────────────────────────

        private void Start()
        {
            if (_handPrefab == null)
            {
                Debug.LogError("[HandAnimationPlayer] Hand Prefab is not assigned!");
                return;
            }

            if (_animatorController == null)
            {
                Debug.LogError("[HandAnimationPlayer] Animator Controller is not assigned!");
                return;
            }

            SetupHand();
        }

        private void Update()
        {
            // Animator ignores clip.wrapMode — it only respects the clip's
            // internal loopTime setting which can't be changed at runtime.
            // So we manually loop by crossfading back to the start.
            if (_loop && _animator != null && _animator.runtimeAnimatorController != null)
            {
                // Don't re-trigger if already blending back to start
                if (_animator.IsInTransition(0))
                    return;

                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                if (stateInfo.normalizedTime >= 1.0f)
                {
                    // Reset position so root motion doesn't accumulate across loops
                    _handInstance.transform.localPosition = _startLocalPos;
                    _handInstance.transform.localRotation = _startLocalRot;

                    if (_loopBlendDuration > 0f)
                    {
                        // Smooth blend: crossfade from end pose back to start pose
                        _animator.CrossFade(stateInfo.shortNameHash, _loopBlendDuration, 0, 0f);
                    }
                    else
                    {
                        // Hard snap back to start
                        _animator.Play(stateInfo.shortNameHash, 0, 0f);
                    }
                }
            }
        }

        private void OnDestroy()
        {
            if (_handInstance != null)
                Destroy(_handInstance);
        }

        // ─── Setup ─────────────────────────────────────────────────────

        private void SetupHand()
        {
            // ── Instantiate INACTIVE so Awake/Start don't fire on tracking components ──
            // This prevents HandVisual.Start() from asserting about missing IHand.
            bool prefabWasActive = _handPrefab.activeSelf;
            _handPrefab.SetActive(false);

            _handInstance = Instantiate(_handPrefab, transform);

            _handPrefab.SetActive(prefabWasActive); // restore prefab state

            _handInstance.name = _handPrefab.name + "_Playback";
            _handInstance.transform.localPosition = Vector3.zero;
            _handInstance.transform.localRotation = Quaternion.identity;

            // ── Disable tracking components BEFORE activating ──────────────
            // XR Hands components
            DisableComponentByName(_handInstance, "XRHandSkeletonDriver");
            DisableComponentByName(_handInstance, "XRHandTrackingEvents");
            DisableComponentByName(_handInstance, "XRHandMeshController");

            // Meta Interaction SDK components
            DisableInteractionSDKComponents(_handInstance);

            // ── NOW activate — only the Animator and SkinnedMeshRenderer run ──
            _handInstance.SetActive(true);

            // Ensure the SkinnedMeshRenderer is visible
            var smr = _handInstance.GetComponentInChildren<SkinnedMeshRenderer>(true);
            if (smr != null)
            {
                smr.enabled = true;

                // Apply material override if set
                if (_handMaterial != null)
                    smr.sharedMaterial = _handMaterial;

                Debug.Log($"[HandAnimationPlayer] Mesh renderer enabled on \"{smr.gameObject.name}\".");
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] No SkinnedMeshRenderer found on hand prefab!");
            }

            // Add Animator and assign the controller
            _animator = _handInstance.GetComponent<Animator>();
            if (_animator == null)
                _animator = _handInstance.AddComponent<Animator>();

            _animator.runtimeAnimatorController = _animatorController;
            _animator.applyRootMotion = true;

            // Force evaluate frame 0 so the hand snaps to its starting pose,
            // then cache that position for loop resets.
            _animator.Update(0f);
            _startLocalPos = _handInstance.transform.localPosition;
            _startLocalRot = _handInstance.transform.localRotation;

            Debug.Log($"[HandAnimationPlayer] Playback ready: {_handInstance.name} with {_animatorController.name} (loop={_loop})");
        }

        // ─── Helpers ────────────────────────────────────────────────────

        /// <summary>
        /// Finds and disables a MonoBehaviour by type name on the given GameObject
        /// or any of its children. Same pattern as HandMeshVisualizer.
        /// </summary>
        private static void DisableComponentByName(GameObject root, string typeName)
        {
            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp != null && comp.GetType().Name == typeName)
                {
                    comp.enabled = false;
                    Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                    return;
                }
            }
        }

        /// <summary>
        /// Also disable Meta Interaction SDK components for OVR hand prefabs.
        /// </summary>
        private static void DisableInteractionSDKComponents(GameObject root)
        {
            string[] componentNames = {
                "HandVisual",
                "HandPuppet",
                "FromOVRHandDataSource",
                "Hand",
                "SyntheticHand",
                "LastKnownGoodHand",
                "FixedScaleHand"
            };

            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp == null) continue;
                string typeName = comp.GetType().Name;
                foreach (var name in componentNames)
                {
                    if (typeName == name)
                    {
                        comp.enabled = false;
                        Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                        break;
                    }
                }
            }
        }
    }
}
