using System.Collections.Generic;
using UnityEngine;

namespace FingerPaint
{
    /// <summary>
    /// Plays back a recorded hand animation clip on an XR Hands prefab.
    ///
    /// Setup:
    ///   1. Add an empty GameObject -> HandAnimationPlayer component.
    ///   2. Assign the hand prefab (Left or Right Hand Tracking prefab).
    ///   3. Assign the AnimatorController generated by HandAnimationRecorder.
    ///   4. Press Play — the hand replays the recorded motion.
    ///
    /// How it works:
    ///   - Instantiates the hand prefab as a child.
    ///   - Disables XR tracking components (XRHandSkeletonDriver, XRHandTrackingEvents,
    ///     XRHandMeshController) so they don't fight with the Animator.
    ///   - Adds an Animator component with the recorded controller.
    ///   - The Animator drives the bone transforms instead of live XR tracking.
    /// </summary>
    public class HandAnimationPlayer : MonoBehaviour
    {
        [Header("Hand Prefab")]
        [Tooltip("XR Hands prefab (Left or Right Hand Tracking) — same one used during recording.")]
        [SerializeField] private GameObject _handPrefab;

        [Header("Animation")]
        [Tooltip("AnimatorController generated by HandAnimationRecorder (the .controller file).")]
        [SerializeField] private RuntimeAnimatorController _animatorController;

        [Tooltip("Loop the animation playback.")]
        [SerializeField] private bool _loop = true;

        [Tooltip("Seconds to blend from end pose back to start pose when looping. 0 = hard snap.")]
        [SerializeField] [Range(0f, 2f)] private float _loopBlendDuration = 0.5f;

        [Header("Voice Audio (optional)")]
        [Tooltip("WAV clip recorded by DualHandAnimationRecorder. Assign on ONE hand player only.")]
        [SerializeField] private AudioClip _voiceClip;

        [Tooltip("Volume for voice playback.")]
        [SerializeField] [Range(0f, 1f)] private float _voiceVolume = 1f;

        [Tooltip("Seconds to wait before starting playback. Gives Quest headset time to finish loading the scene.")]
        [SerializeField] [Range(0f, 10f)] private float _startDelay = 2f;

        [Tooltip("Shift audio relative to animation (seconds). Positive = audio plays later, negative = earlier. Adjustable at runtime in Inspector.")]
        [SerializeField] [Range(-2f, 2f)] private float _audioOffset = 0f;

        [Header("Subtitles (optional)")]
        [Tooltip("SRT subtitle file imported as TextAsset. Rename your .srt to .srt.txt so Unity imports it.")]
        [SerializeField] private TextAsset _subtitleFile;

        [Tooltip("Reference to a SubtitleDisplay component in the scene.")]
        [SerializeField] private SubtitleDisplay _subtitleDisplay;

        [Header("Partner Sync")]
        [Tooltip("The other hand's HandAnimationPlayer. If left empty, auto-discovers at Start. " +
                 "Both hands loop together — whichever has audio determines the loop point.")]
        [SerializeField] private HandAnimationPlayer _partnerPlayer;

        [Header("Clear Canvas on Loop")]
        [Tooltip("When enabled, prompts the player before each loop: save & clear the canvas, or keep sculpting. " +
                 "Only needs to be on ONE player — if both are checked, only one will show the prompt.")]
        [SerializeField] private bool _clearCanvasOnLoop = false;

        [Tooltip("How long the prompt stays visible (seconds). The prompt appears this many seconds before the loop ends.")]
        [SerializeField] [Range(3f, 30f)] private float _clearPromptDuration = 8f;

        [Tooltip("Reference to the FingerPainter to clear. Auto-discovered if empty.")]
        [SerializeField] private FingerPainter _painter;

        [Tooltip("Reference to MeshExporter for saving before clear. Auto-discovered if empty.")]
        [SerializeField] private MeshExporter _meshExporter;

        [Tooltip("Reference to HandTrackingManager for thumbs-up detection. Auto-discovered if empty.")]
        [SerializeField] private HandTrackingManager _handTracking;

        [Tooltip("Reference to ActionFeedbackUI for showing the prompt. Auto-discovered if empty.")]
        [SerializeField] private ActionFeedbackUI _feedbackUI;

        [Header("Height Follow")]
        [Tooltip("When enabled, the hand animation follows the player's height changes. " +
                 "If you stand up, the hands move up too, keeping them at eye level.")]
        [SerializeField] private bool _followPlayerHeight = false;

        [Tooltip("Smoothing speed for height follow. Higher = snappier.")]
        [SerializeField] [Range(1f, 20f)] private float _heightFollowSpeed = 8f;

        [Header("Material Override")]
        [Tooltip("Optional material to apply to the hand mesh. Leave null for the prefab default.")]
        [SerializeField] private Material _handMaterial;

        // ─── Runtime state ──────────────────────────────────────────────

        private GameObject _handInstance;
        private Animator _animator;
        private AudioSource _audioSource;
        private bool _playbackStartPending;
        private float _pendingStartTime;
        private List<SrtParser.SrtEntry> _subtitleEntries;
        private float _effectiveLoopDuration = -1f; // min(animLength, audioLength)
        private bool _loopDurationResolved;
        private bool _isLoopingFromPartner; // prevent infinite recursion
        private Transform _cachedXROrigin;
        private Vector3 _lastKnownXROriginPos;
        private Quaternion _lastKnownXROriginRot;
        private float _savedSpeed = 1f; // speed before pausing
        private bool _isPaused;

        // Height follow
        private Transform _heightCamera;
        private float _initialCameraY;
        private float _initialSelfY;
        private bool _heightBaselineCaptured;

        // Clear canvas on loop
        private bool _clearPromptShown;
        private bool _keepSculptingChosen;
        private bool _isClearCanvasOwner; // only one player handles the prompt

        // ─── Public API ─────────────────────────────────────────────────

        /// <summary>
        /// Swap the AnimatorController at runtime to play a different recording.
        /// </summary>
        public void SetAnimatorController(RuntimeAnimatorController controller)
        {
            _animatorController = controller;
            if (_animator != null)
                _animator.runtimeAnimatorController = controller;
        }

        /// <summary>
        /// Restart playback from the beginning (animation + voice).
        /// Also restarts the partner player if one is linked.
        /// </summary>
        public void Restart()
        {
            RestartSelf();
            // Also restart partner (without recursion)
            if (_partnerPlayer != null && !_isLoopingFromPartner)
            {
                _partnerPlayer._isLoopingFromPartner = true;
                _partnerPlayer.RestartSelf();
                _partnerPlayer._isLoopingFromPartner = false;
            }
        }

        /// <summary>
        /// Restart just this player (no partner sync). Used internally.
        /// Uses Play (hard snap to frame 0) — CrossFade to the same state
        /// doesn't reliably restart in Unity and caused XR Origin displacement.
        /// </summary>
        private void RestartSelf()
        {
            if (_animator != null)
            {
                // Save XR Origin position before the animator transition
                Transform xrOrigin = _cachedXROrigin;
                Vector3 savedPos = Vector3.zero;
                Quaternion savedRot = Quaternion.identity;
                bool hasXR = xrOrigin != null;
                if (hasXR)
                {
                    savedPos = xrOrigin.position;
                    savedRot = xrOrigin.rotation;
                }

                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                _animator.Play(stateInfo.shortNameHash, 0, 0f);

                // Restore XR Origin if it got displaced
                if (hasXR)
                {
                    if (Vector3.Distance(xrOrigin.position, savedPos) > 0.01f)
                    {
                        Debug.LogWarning($"[HandAnimationPlayer] XR Origin was displaced from {savedPos} to {xrOrigin.position} during loop restart — restoring.");
                        xrOrigin.position = savedPos;
                        xrOrigin.rotation = savedRot;
                    }
                }
            }
            RestartAudio();
        }

        /// <summary>
        /// Effective loop duration resolved by the player with audio.
        /// The partner reads this to know when to loop.
        /// </summary>
        public float EffectiveLoopDuration => _effectiveLoopDuration;
        public bool HasLoopDurationResolved => _loopDurationResolved;

        /// <summary>
        /// Pause or resume playback (animation + voice).
        /// Remembers the speed before pausing so resume restores it (e.g. 5x).
        /// Also pauses/resumes the partner player.
        /// </summary>
        public void SetPaused(bool paused, bool syncPartner = true)
        {
            _isPaused = paused;

            if (_animator != null)
            {
                if (paused)
                {
                    _savedSpeed = _animator.speed > 0f ? _animator.speed : 1f;
                    _animator.speed = 0f;
                }
                else
                {
                    _animator.speed = _savedSpeed;
                }
            }

            if (_audioSource != null && _audioSource.clip != null)
            {
                if (paused)
                {
                    _audioSource.Pause();
                }
                else
                {
                    _audioSource.pitch = _savedSpeed;
                    _audioSource.UnPause();
                }
            }

            if (syncPartner && _partnerPlayer != null)
                _partnerPlayer.SetPaused(paused, false);
        }

        // ─── Lifecycle ──────────────────────────────────────────────────

        private void Start()
        {
            if (_handPrefab == null)
            {
                Debug.LogError("[HandAnimationPlayer] Hand Prefab is not assigned!");
                return;
            }

            if (_animatorController == null)
            {
                Debug.LogError("[HandAnimationPlayer] Animator Controller is not assigned!");
                return;
            }

            SetupHand();

            // Cache XR Origin so we can protect it from teleportation during loop restarts
            CacheXROrigin();

            // Auto-discover partner if not manually assigned
            if (_partnerPlayer == null)
            {
                foreach (var player in FindObjectsOfType<HandAnimationPlayer>())
                {
                    if (player != this)
                    {
                        _partnerPlayer = player;
                        Debug.Log($"[HandAnimationPlayer] Auto-linked partner: {player.name}");
                        break;
                    }
                }
            }

            // Parse subtitle file if assigned
            if (_subtitleFile != null)
                _subtitleEntries = SrtParser.Parse(_subtitleFile.text);

            // Auto-discover clear canvas references
            SetupClearCanvasOnLoop();
        }

        private void Update()
        {
            if (_animator == null) return;

            // ── Start delay: wait for Quest headset to finish loading ─────
            if (_playbackStartPending)
            {
                if (Time.time - _pendingStartTime < _startDelay)
                    return; // still waiting

                // Start both animation and audio at the same moment
                _animator.speed = 1f;

                if (_audioSource != null)
                {
                    if (_audioOffset > 0f)
                    {
                        // Audio should lag behind animation — delay audio start
                        _audioSource.PlayDelayed(_audioOffset);
                    }
                    else if (_audioOffset < 0f)
                    {
                        // Audio should lead animation — start audio and seek ahead
                        _audioSource.Play();
                        _audioSource.time = -_audioOffset;
                    }
                    else
                    {
                        _audioSource.Play();
                    }
                }

                _playbackStartPending = false;

                // Capture height baseline now that the player is settled in
                CaptureHeightBaseline();

                Debug.Log($"[HandAnimationPlayer] Playback started after {_startDelay}s delay (audioOffset={_audioOffset:F2}s)");
                return;
            }

            // ── Height follow ──────────────────────────────────────────────
            UpdateHeightFollow();

            // ── Runtime audio offset correction ──────────────────────────
            // If the user adjusts _audioOffset in the Inspector at runtime,
            // continuously nudge the audio time to stay in sync.
            // (Skip during transitions, as normalizedTime is unreliable while blending)
            if (!_animator.IsInTransition(0) && _audioSource != null && _audioSource.isPlaying && _animator.runtimeAnimatorController != null)
            {
                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                
                // Use modulo 1.0f so if the animator state exceeds 1.0 (e.g. before loop resets),
                // we don't calculate an expected audio time past the end of the clip.
                float animTime = (stateInfo.normalizedTime % 1.0f) * stateInfo.length;
                float expectedAudioTime = animTime - _audioOffset;

                if (expectedAudioTime >= 0f && expectedAudioTime < _audioSource.clip.length)
                {
                    float drift = _audioSource.time - expectedAudioTime;
                    // Only correct if drift exceeds 100ms to avoid constant jitter
                    if (Mathf.Abs(drift) > 0.1f)
                    {
                        _audioSource.time = expectedAudioTime;
                    }
                }
            }

            // ── Subtitle update ─────────────────────────────────────────
            if (_subtitleEntries != null && _subtitleDisplay != null && _audioSource != null)
            {
                float subTime = _audioSource.isPlaying ? _audioSource.time : -1f;
                string text = SrtParser.GetTextAtTime(_subtitleEntries, subTime);
                _subtitleDisplay.SetText(text);
            }

            // ── Loop handling ────────────────────────────────────────────
            if (_loop && _animator.runtimeAnimatorController != null)
            {
                // Don't trigger loop when paused
                if (_isPaused)
                    return;

                // If partner triggered our restart, skip own loop detection this frame
                if (_isLoopingFromPartner)
                    return;

                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                float animLength = stateInfo.length;

                // Resolve effective loop duration once we know both lengths
                if (!_loopDurationResolved && animLength > 0f)
                {
                    _effectiveLoopDuration = animLength;
                    if (_audioSource != null && _audioSource.clip != null)
                    {
                        float audioEffective = _audioSource.clip.length + _audioOffset;
                        _effectiveLoopDuration = Mathf.Min(animLength, audioEffective);
                        _effectiveLoopDuration = Mathf.Max(_effectiveLoopDuration, 0.5f);
                        Debug.Log($"[HandAnimationPlayer] Loop duration: {_effectiveLoopDuration:F2}s " +
                                  $"(anim={animLength:F2}s, audio={_audioSource.clip.length:F2}s, offset={_audioOffset:F2}s)");
                    }
                    else if (_partnerPlayer != null && _partnerPlayer.HasLoopDurationResolved
                             && _partnerPlayer.EffectiveLoopDuration > 0f)
                    {
                        // No audio on this player — adopt partner's loop duration
                        _effectiveLoopDuration = Mathf.Min(animLength, _partnerPlayer.EffectiveLoopDuration);
                        _effectiveLoopDuration = Mathf.Max(_effectiveLoopDuration, 0.5f);
                        Debug.Log($"[HandAnimationPlayer] Loop duration (from partner): {_effectiveLoopDuration:F2}s " +
                                  $"(own anim={animLength:F2}s, partner={_partnerPlayer.EffectiveLoopDuration:F2}s)");
                    }
                    else
                    {
                        Debug.Log($"[HandAnimationPlayer] Loop duration: {_effectiveLoopDuration:F2}s (no audio, using anim length)");
                    }
                    _loopDurationResolved = true;
                }

                // If partner hasn't resolved yet but now has, re-check our duration
                if (_loopDurationResolved && _audioSource == null
                    && _partnerPlayer != null && _partnerPlayer.HasLoopDurationResolved
                    && _partnerPlayer.EffectiveLoopDuration > 0f
                    && _effectiveLoopDuration > _partnerPlayer.EffectiveLoopDuration)
                {
                    _effectiveLoopDuration = Mathf.Min(animLength, _partnerPlayer.EffectiveLoopDuration);
                    _effectiveLoopDuration = Mathf.Max(_effectiveLoopDuration, 0.5f);
                }

                // Check if we've reached the effective loop point
                float animTime = stateInfo.normalizedTime * animLength;
                bool shouldLoop = false;

                if (_effectiveLoopDuration > 0f && animTime >= _effectiveLoopDuration)
                {
                    shouldLoop = true;
                }
                else if (stateInfo.normalizedTime >= 1.0f)
                {
                    shouldLoop = true;
                }

                // Audio finished before animation (audio shorter)
                if (!shouldLoop && _audioSource != null && _audioSource.clip != null
                    && !_audioSource.isPlaying && _loopDurationResolved
                    && _effectiveLoopDuration < animLength)
                {
                    shouldLoop = true;
                }

                // ── Clear canvas prompt (shown before loop end) ───────────
                if (_isClearCanvasOwner && _loopDurationResolved && _effectiveLoopDuration > 0f)
                {
                    float timeLeft = _effectiveLoopDuration - animTime;
                    UpdateClearCanvasPrompt(timeLeft, shouldLoop);
                }

                if (shouldLoop)
                {
                    // If clear canvas is active and user didn't keep, save & clear
                    if (_isClearCanvasOwner && _clearCanvasOnLoop && !_keepSculptingChosen)
                    {
                        PerformSaveAndClear();
                    }

                    // Reset prompt state for next loop
                    _clearPromptShown = false;
                    _keepSculptingChosen = false;

                    // Restart self + partner via Restart()
                    Restart();
                }
            }
        }

        /// <summary>
        /// Safeguard: if the XR Origin position jumps by more than 1m in a single frame,
        /// it was likely displaced by an animation glitch — restore it.
        /// </summary>
        private void LateUpdate()
        {
            if (_cachedXROrigin == null) return;

            float dist = Vector3.Distance(_cachedXROrigin.position, _lastKnownXROriginPos);
            if (dist > 1f)
            {
                Debug.LogWarning($"[HandAnimationPlayer] XR Origin jumped {dist:F1}m in one frame " +
                                 $"(from {_lastKnownXROriginPos} to {_cachedXROrigin.position}) — restoring!");
                _cachedXROrigin.position = _lastKnownXROriginPos;
                _cachedXROrigin.rotation = _lastKnownXROriginRot;
            }
            else
            {
                // Track the good position
                _lastKnownXROriginPos = _cachedXROrigin.position;
                _lastKnownXROriginRot = _cachedXROrigin.rotation;
            }
        }

        private void OnDestroy()
        {
            if (_handInstance != null)
                Destroy(_handInstance);

            if (_audioSource != null)
                Destroy(_audioSource);

            if (_subtitleDisplay != null)
                _subtitleDisplay.Clear();
        }

        private void RestartAudio()
        {
            if (_audioSource != null && _audioSource.clip != null)
            {
                if (_audioOffset > 0f)
                {
                    _audioSource.Stop();
                    _audioSource.PlayDelayed(_audioOffset);
                }
                else if (_audioOffset < 0f)
                {
                    _audioSource.time = -_audioOffset;
                    _audioSource.Play();
                }
                else
                {
                    _audioSource.time = 0f;
                    _audioSource.Play();
                }
            }
        }

        // ─── Setup ─────────────────────────────────────────────────────

        private void SetupHand()
        {
            // ── Instantiate INACTIVE so Awake/Start don't fire on tracking components ──
            // This prevents HandVisual.Start() from asserting about missing IHand.
            bool prefabWasActive = _handPrefab.activeSelf;
            _handPrefab.SetActive(false);

            _handInstance = Instantiate(_handPrefab, transform);

            _handPrefab.SetActive(prefabWasActive); // restore prefab state

            _handInstance.name = _handPrefab.name + "_Playback";
            _handInstance.transform.localPosition = Vector3.zero;
            _handInstance.transform.localRotation = Quaternion.identity;

            // ── Disable tracking components BEFORE activating ──────────────
            // XR Hands components
            DisableComponentByName(_handInstance, "XRHandSkeletonDriver");
            DisableComponentByName(_handInstance, "XRHandTrackingEvents");
            DisableComponentByName(_handInstance, "XRHandMeshController");

            // Meta Interaction SDK components
            DisableInteractionSDKComponents(_handInstance);

            // ── NOW activate — only the Animator and SkinnedMeshRenderer run ──
            _handInstance.SetActive(true);

            // Ensure the SkinnedMeshRenderer is visible
            var smr = _handInstance.GetComponentInChildren<SkinnedMeshRenderer>(true);
            if (smr != null)
            {
                smr.enabled = true;

                // Apply material override if set
                if (_handMaterial != null)
                    smr.sharedMaterial = _handMaterial;

                Debug.Log($"[HandAnimationPlayer] Mesh renderer enabled on \"{smr.gameObject.name}\".");
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] No SkinnedMeshRenderer found on hand prefab!");
            }

            // ── Determine the animation root ─────────────────────────────────
            // The Meta recorder (HandAnimationRecorder / DualHandAnimationRecorder)
            // writes curve paths relative to HandVisual.Root. Crucially,
            // HandVisual.Root is the PARENT of the wrist bone, not the wrist
            // itself. So recorded paths look like:
            //   path ""                              → HandVisual.Root (parent of wrist)
            //   path "XRHand_Wrist"                  → the wrist bone
            //   path "XRHand_Wrist/XRHand_Palm"      → palm under wrist
            //   path "XRHand_Wrist/XRHand_ThumbMeta…" → finger bones
            //
            // SkinnedMeshRenderer.rootBone points to XRHand_Wrist (the wrist
            // bone itself), so we go one level UP to its parent to match
            // HandVisual.Root. The Animator must sit there for all curve
            // paths to resolve correctly.
            Transform animRoot = _handInstance.transform;
            if (smr != null && smr.rootBone != null)
            {
                // smr.rootBone = XRHand_Wrist; we need its parent = HandVisual.Root
                if (smr.rootBone.parent != null)
                {
                    animRoot = smr.rootBone.parent;
                    Debug.Log($"[HandAnimationPlayer] Animation root: \"{animRoot.name}\" " +
                              $"(parent of rootBone \"{smr.rootBone.name}\")");
                }
                else
                {
                    animRoot = smr.rootBone;
                    Debug.LogWarning($"[HandAnimationPlayer] rootBone \"{smr.rootBone.name}\" has no parent — " +
                                     "using it directly. Finger curves may not resolve.");
                }
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] No rootBone found — Animator will be on the prefab root. " +
                                 "Finger curves may not resolve if they were recorded relative to a child bone.");
            }

            // Add Animator on the animation root (not the prefab root)
            _animator = animRoot.GetComponent<Animator>();
            if (_animator == null)
                _animator = animRoot.gameObject.AddComponent<Animator>();

            _animator.runtimeAnimatorController = _animatorController;

            // applyRootMotion = false ensures root position/rotation curves
            // (path "") are applied as regular property animations — absolute
            // local-position values from the clip, NOT accumulated deltas.
            // This preserves the world-space positions recorded during capture,
            // so both hands maintain correct relative positioning.
            _animator.applyRootMotion = false;

            // Snap to frame 0 pose, then pause until start delay elapses
            _animator.Update(0f);
            _animator.speed = 0f;

            // ── Voice audio ──────────────────────────────────────────────────
            if (_voiceClip != null)
            {
                _audioSource = gameObject.AddComponent<AudioSource>();
                _audioSource.clip = _voiceClip;
                _audioSource.volume = _voiceVolume;
                _audioSource.loop = false;       // we handle loop-sync manually
                _audioSource.playOnAwake = false;
                _audioSource.spatialBlend = 0f;  // 2D audio (non-spatial)

                // Bypass Meta XR Audio spatial processing which attenuates volume
                _audioSource.bypassEffects = true;
                _audioSource.bypassListenerEffects = true;
                _audioSource.bypassReverbZones = true;

                // Remove MetaXRAudioSource if Meta's plugin auto-added it
                DisableComponentByName(gameObject, "MetaXRAudioSource");
            }

            // Both animation and audio wait for _startDelay before playing
            _playbackStartPending = true;
            _pendingStartTime = Time.time;

            Debug.Log($"[HandAnimationPlayer] Playback ready: {_handInstance.name} with {_animatorController.name} " +
                      $"(loop={_loop}, animRoot={animRoot.name}, startDelay={_startDelay}s)");
        }

        // ─── Clear Canvas on Loop ────────────────────────────────────────

        private void SetupClearCanvasOnLoop()
        {
            if (!_clearCanvasOnLoop) return;

            // Determine ownership: only one player shows the prompt
            // If partner also has it enabled, the one with audio owns it;
            // if neither has audio, the first one (this) owns it.
            if (_partnerPlayer != null && _partnerPlayer._clearCanvasOnLoop)
            {
                // I have audio → I'm the owner
                if (_voiceClip != null)
                {
                    _isClearCanvasOwner = true;
                }
                // Partner has audio → they're the owner
                else if (_partnerPlayer._voiceClip != null)
                {
                    _isClearCanvasOwner = false;
                }
                // Neither has audio → use instance ID as tiebreaker
                else
                {
                    _isClearCanvasOwner = GetInstanceID() < _partnerPlayer.GetInstanceID();
                }
            }
            else
            {
                _isClearCanvasOwner = true;
            }

            if (!_isClearCanvasOwner) return;

            // Auto-discover references
            if (_painter == null)
                _painter = FindObjectOfType<FingerPainter>();
            if (_meshExporter == null)
                _meshExporter = FindObjectOfType<MeshExporter>();
            if (_handTracking == null)
                _handTracking = FindObjectOfType<HandTrackingManager>();
            if (_feedbackUI == null)
                _feedbackUI = FindObjectOfType<ActionFeedbackUI>();

            if (_painter == null)
                Debug.LogWarning("[HandAnimationPlayer] ClearCanvasOnLoop: no FingerPainter found!");
            if (_feedbackUI == null)
                Debug.LogWarning("[HandAnimationPlayer] ClearCanvasOnLoop: no ActionFeedbackUI found!");

            Debug.Log($"[HandAnimationPlayer] Clear canvas on loop: owner={_isClearCanvasOwner}, " +
                      $"leadTime={_clearPromptDuration}s");
        }

        /// <summary>
        /// Shows the prompt when approaching the loop end, checks for thumbs-up to cancel.
        /// </summary>
        private void UpdateClearCanvasPrompt(float timeLeft, bool isAtLoopEnd)
        {
            if (!_clearCanvasOnLoop) return;

            // Show prompt when we're within the lead time
            if (timeLeft <= _clearPromptDuration && timeLeft > 0f && !_clearPromptShown)
            {
                _clearPromptShown = true;
                _keepSculptingChosen = false;

                if (_feedbackUI != null)
                    _feedbackUI.Show("Keep sculpting? Thumbs up = Keep", _clearPromptDuration);

                Debug.Log("[HandAnimationPlayer] Clear canvas prompt shown.");
            }

            // While prompt is shown, check for thumbs-up on either hand
            if (_clearPromptShown && !_keepSculptingChosen && _handTracking != null)
            {
                bool thumbsUp = _handTracking.IsThumbsUp(true) || _handTracking.IsThumbsUp(false);
                if (thumbsUp)
                {
                    _keepSculptingChosen = true;

                    if (_feedbackUI != null)
                        _feedbackUI.Show("Keeping your work!");

                    Debug.Log("[HandAnimationPlayer] User chose to keep sculpting.");
                }
            }
        }

        private void PerformSaveAndClear()
        {
            if (_painter == null) return;

            int securedCount = _painter.TotalPointCount;

            if (securedCount == 0)
            {
                // Nothing secured — no save, no clear needed
                Debug.Log("[HandAnimationPlayer] No secured spheres — skipping save & clear.");
                return;
            }

            // Save first, then clear
            if (_meshExporter != null)
            {
                _meshExporter.Export();
                Debug.Log($"[HandAnimationPlayer] Saved {securedCount} points before clear.");

                if (_feedbackUI != null)
                    _feedbackUI.Show("Saved & Clearing");
            }
            else if (_feedbackUI != null)
            {
                _feedbackUI.Show("Clearing canvas");
            }

            _painter.ClearAll();
            Debug.Log("[HandAnimationPlayer] Canvas cleared on loop.");
        }

        // ─── Height Follow ───────────────────────────────────────────────

        /// <summary>
        /// Captures the camera's current Y position as the baseline.
        /// Future height changes are measured as deltas from this.
        /// </summary>
        private void CaptureHeightBaseline()
        {
            if (!_followPlayerHeight) return;

            _heightCamera = Camera.main != null ? Camera.main.transform : null;
            if (_heightCamera == null)
            {
                foreach (var cam in FindObjectsOfType<Camera>())
                {
                    if (cam.isActiveAndEnabled)
                    {
                        _heightCamera = cam.transform;
                        break;
                    }
                }
            }

            if (_heightCamera != null)
            {
                _initialCameraY = _heightCamera.position.y;
                _initialSelfY = transform.position.y;
                _heightBaselineCaptured = true;
                Debug.Log($"[HandAnimationPlayer] Height baseline captured: cameraY={_initialCameraY:F3}, selfY={_initialSelfY:F3}");
            }
        }

        /// <summary>
        /// Smoothly offsets this transform's Y position based on the delta
        /// between the camera's current height and the baseline height.
        /// </summary>
        private void UpdateHeightFollow()
        {
            if (!_followPlayerHeight || !_heightBaselineCaptured || _heightCamera == null)
                return;

            float cameraHeightDelta = _heightCamera.position.y - _initialCameraY;
            float targetY = _initialSelfY + cameraHeightDelta;

            Vector3 pos = transform.position;
            pos.y = Mathf.Lerp(pos.y, targetY, _heightFollowSpeed * Time.deltaTime);
            transform.position = pos;
        }

        // ─── XR Origin Protection ────────────────────────────────────────

        /// <summary>
        /// Find the XR Origin in the scene by searching for common component names.
        /// </summary>
        private void CacheXROrigin()
        {
            // Try to find by component type name (works across XR SDK versions)
            string[] xrOriginTypeNames = { "XROrigin", "XRRig", "OVRCameraRig", "TrackedPoseDriver" };

            foreach (var typeName in xrOriginTypeNames)
            {
                foreach (var mb in FindObjectsOfType<MonoBehaviour>())
                {
                    if (mb != null && mb.GetType().Name == typeName)
                    {
                        // For TrackedPoseDriver, use its parent (the XR Origin root)
                        _cachedXROrigin = typeName == "TrackedPoseDriver"
                            ? mb.transform.root
                            : mb.transform;

                        _lastKnownXROriginPos = _cachedXROrigin.position;
                        _lastKnownXROriginRot = _cachedXROrigin.rotation;
                        Debug.Log($"[HandAnimationPlayer] Cached XR Origin: \"{_cachedXROrigin.name}\" " +
                                  $"(found via {typeName}) at {_lastKnownXROriginPos}");
                        return;
                    }
                }
            }

            // Fallback: search by name
            var go = GameObject.Find("XR Origin (XR Rig)") ?? GameObject.Find("XR Origin") ?? GameObject.Find("OVRCameraRig");
            if (go != null)
            {
                _cachedXROrigin = go.transform;
                _lastKnownXROriginPos = _cachedXROrigin.position;
                _lastKnownXROriginRot = _cachedXROrigin.rotation;
                Debug.Log($"[HandAnimationPlayer] Cached XR Origin by name: \"{go.name}\" at {_lastKnownXROriginPos}");
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] Could not find XR Origin — position protection disabled.");
            }
        }

        // ─── Debug / Editor Playback Control ─────────────────────────────

        /// <summary>Current animation time in seconds.</summary>
        public float CurrentTime
        {
            get
            {
                if (_animator == null || _animator.runtimeAnimatorController == null) return 0f;
                var info = _animator.GetCurrentAnimatorStateInfo(0);
                return (info.normalizedTime % 1f) * info.length;
            }
        }

        /// <summary>Total animation clip length in seconds.</summary>
        public float AnimationLength
        {
            get
            {
                if (_animator == null || _animator.runtimeAnimatorController == null) return 0f;
                var info = _animator.GetCurrentAnimatorStateInfo(0);
                return info.length;
            }
        }

        /// <summary>Total audio clip length in seconds (0 if no audio).</summary>
        public float AudioLength => (_audioSource != null && _audioSource.clip != null) ? _audioSource.clip.length : 0f;

        /// <summary>Current audio playback time.</summary>
        public float AudioTime => (_audioSource != null && _audioSource.isPlaying) ? _audioSource.time : 0f;

        /// <summary>Whether playback has started (past start delay). True even when paused.</summary>
        public bool IsPlaying => _animator != null && !_playbackStartPending;

        /// <summary>
        /// Seek both animation and audio to a specific time (seconds).
        /// Also seeks the partner player.
        /// </summary>
        public void SeekTo(float timeInSeconds, bool syncPartner = true)
        {
            if (_animator == null || _animator.runtimeAnimatorController == null) return;

            var info = _animator.GetCurrentAnimatorStateInfo(0);
            float length = info.length;
            if (length <= 0f) return;

            float normalized = Mathf.Clamp01(timeInSeconds / length);
            _animator.Play(info.shortNameHash, 0, normalized);

            if (_audioSource != null && _audioSource.clip != null)
            {
                float audioTime = Mathf.Clamp(timeInSeconds - _audioOffset, 0f, _audioSource.clip.length);
                _audioSource.time = audioTime;
                if (!_audioSource.isPlaying && !_isPaused)
                    _audioSource.Play();
            }

            if (syncPartner && _partnerPlayer != null)
                _partnerPlayer.SeekTo(timeInSeconds, false);
        }

        /// <summary>
        /// Set playback speed (1 = normal, 2 = double, etc.)
        /// Also applies to partner if linked.
        /// </summary>
        public void SetPlaybackSpeed(float speed, bool syncPartner = true)
        {
            _savedSpeed = speed;

            if (_animator != null && !_isPaused)
                _animator.speed = speed;

            if (_audioSource != null && _audioSource.clip != null && !_isPaused)
                _audioSource.pitch = speed;

            if (syncPartner && _partnerPlayer != null)
                _partnerPlayer.SetPlaybackSpeed(speed, false);
        }

        /// <summary>Current playback speed (returns saved speed even when paused).</summary>
        public float PlaybackSpeed => _isPaused ? 0f : (_animator != null ? _animator.speed : 1f);

        /// <summary>Whether playback is currently paused.</summary>
        public bool IsPaused => _isPaused;

        // ─── Helpers ────────────────────────────────────────────────────

        /// <summary>
        /// Finds and disables a MonoBehaviour by type name on the given GameObject
        /// or any of its children. Same pattern as HandMeshVisualizer.
        /// </summary>
        private static void DisableComponentByName(GameObject root, string typeName)
        {
            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp != null && comp.GetType().Name == typeName)
                {
                    comp.enabled = false;
                    Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                    return;
                }
            }
        }

        /// <summary>
        /// Also disable Meta Interaction SDK components for OVR hand prefabs.
        /// </summary>
        private static void DisableInteractionSDKComponents(GameObject root)
        {
            string[] componentNames = {
                "HandVisual",
                "HandPuppet",
                "FromOVRHandDataSource",
                "Hand",
                "SyntheticHand",
                "LastKnownGoodHand",
                "FixedScaleHand"
            };

            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp == null) continue;
                string typeName = comp.GetType().Name;
                foreach (var name in componentNames)
                {
                    if (typeName == name)
                    {
                        comp.enabled = false;
                        Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                        break;
                    }
                }
            }
        }
    }
}
