using UnityEngine;

namespace FingerPaint
{
    /// <summary>
    /// Plays back a recorded hand animation clip on an XR Hands prefab.
    ///
    /// Setup:
    ///   1. Add an empty GameObject -> HandAnimationPlayer component.
    ///   2. Assign the hand prefab (Left or Right Hand Tracking prefab).
    ///   3. Assign the AnimatorController generated by HandAnimationRecorder.
    ///   4. Press Play — the hand replays the recorded motion.
    ///
    /// How it works:
    ///   - Instantiates the hand prefab as a child.
    ///   - Disables XR tracking components (XRHandSkeletonDriver, XRHandTrackingEvents,
    ///     XRHandMeshController) so they don't fight with the Animator.
    ///   - Adds an Animator component with the recorded controller.
    ///   - The Animator drives the bone transforms instead of live XR tracking.
    /// </summary>
    public class HandAnimationPlayer : MonoBehaviour
    {
        [Header("Hand Prefab")]
        [Tooltip("XR Hands prefab (Left or Right Hand Tracking) — same one used during recording.")]
        [SerializeField] private GameObject _handPrefab;

        [Header("Animation")]
        [Tooltip("AnimatorController generated by HandAnimationRecorder (the .controller file).")]
        [SerializeField] private RuntimeAnimatorController _animatorController;

        [Tooltip("Loop the animation playback.")]
        [SerializeField] private bool _loop = true;

        [Tooltip("Seconds to blend from end pose back to start pose when looping. 0 = hard snap.")]
        [SerializeField] [Range(0f, 2f)] private float _loopBlendDuration = 0.5f;

        [Header("Voice Audio (optional)")]
        [Tooltip("WAV clip recorded by DualHandAnimationRecorder. Assign on ONE hand player only.")]
        [SerializeField] private AudioClip _voiceClip;

        [Tooltip("Volume for voice playback.")]
        [SerializeField] [Range(0f, 1f)] private float _voiceVolume = 1f;

        [Tooltip("Seconds to wait before starting playback. Gives Quest headset time to finish loading the scene.")]
        [SerializeField] [Range(0f, 10f)] private float _startDelay = 2f;

        [Tooltip("Shift audio relative to animation (seconds). Positive = audio plays later, negative = earlier. Adjustable at runtime in Inspector.")]
        [SerializeField] [Range(-2f, 2f)] private float _audioOffset = 0f;

        [Header("Material Override")]
        [Tooltip("Optional material to apply to the hand mesh. Leave null for the prefab default.")]
        [SerializeField] private Material _handMaterial;

        // ─── Runtime state ──────────────────────────────────────────────

        private GameObject _handInstance;
        private Animator _animator;
        private AudioSource _audioSource;
        private bool _playbackStartPending;
        private float _pendingStartTime;

        // ─── Public API ─────────────────────────────────────────────────

        /// <summary>
        /// Swap the AnimatorController at runtime to play a different recording.
        /// </summary>
        public void SetAnimatorController(RuntimeAnimatorController controller)
        {
            _animatorController = controller;
            if (_animator != null)
                _animator.runtimeAnimatorController = controller;
        }

        /// <summary>
        /// Restart playback from the beginning (animation + voice).
        /// </summary>
        public void Restart()
        {
            if (_animator != null)
                _animator.Play(_animator.GetCurrentAnimatorStateInfo(0).shortNameHash, 0, 0f);
            RestartAudio();
        }

        /// <summary>
        /// Pause or resume playback (animation + voice).
        /// </summary>
        public void SetPaused(bool paused)
        {
            if (_animator != null)
                _animator.speed = paused ? 0f : 1f;

            if (_audioSource != null && _audioSource.clip != null)
            {
                if (paused) _audioSource.Pause();
                else _audioSource.UnPause();
            }
        }

        // ─── Lifecycle ──────────────────────────────────────────────────

        private void Start()
        {
            if (_handPrefab == null)
            {
                Debug.LogError("[HandAnimationPlayer] Hand Prefab is not assigned!");
                return;
            }

            if (_animatorController == null)
            {
                Debug.LogError("[HandAnimationPlayer] Animator Controller is not assigned!");
                return;
            }

            SetupHand();
        }

        private void Update()
        {
            if (_animator == null) return;

            // ── Start delay: wait for Quest headset to finish loading ─────
            if (_playbackStartPending)
            {
                if (Time.time - _pendingStartTime < _startDelay)
                    return; // still waiting

                // Start both animation and audio at the same moment
                _animator.speed = 1f;

                if (_audioSource != null)
                {
                    if (_audioOffset > 0f)
                    {
                        // Audio should lag behind animation — delay audio start
                        _audioSource.PlayDelayed(_audioOffset);
                    }
                    else if (_audioOffset < 0f)
                    {
                        // Audio should lead animation — start audio and seek ahead
                        _audioSource.Play();
                        _audioSource.time = -_audioOffset;
                    }
                    else
                    {
                        _audioSource.Play();
                    }
                }

                _playbackStartPending = false;
                Debug.Log($"[HandAnimationPlayer] Playback started after {_startDelay}s delay (audioOffset={_audioOffset:F2}s)");
                return;
            }

            // ── Runtime audio offset correction ──────────────────────────
            // If the user adjusts _audioOffset in the Inspector at runtime,
            // continuously nudge the audio time to stay in sync.
            // (Skip during transitions, as normalizedTime is unreliable while blending)
            if (!_animator.IsInTransition(0) && _audioSource != null && _audioSource.isPlaying && _animator.runtimeAnimatorController != null)
            {
                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                
                // Use modulo 1.0f so if the animator state exceeds 1.0 (e.g. before loop resets),
                // we don't calculate an expected audio time past the end of the clip.
                float animTime = (stateInfo.normalizedTime % 1.0f) * stateInfo.length;
                float expectedAudioTime = animTime - _audioOffset;

                if (expectedAudioTime >= 0f && expectedAudioTime < _audioSource.clip.length)
                {
                    float drift = _audioSource.time - expectedAudioTime;
                    // Only correct if drift exceeds 100ms to avoid constant jitter
                    if (Mathf.Abs(drift) > 0.1f)
                    {
                        _audioSource.time = expectedAudioTime;
                    }
                }
            }

            // ── Loop handling ────────────────────────────────────────────
            if (_loop && _animator.runtimeAnimatorController != null)
            {
                if (_animator.IsInTransition(0))
                    return;

                var stateInfo = _animator.GetCurrentAnimatorStateInfo(0);
                if (stateInfo.normalizedTime >= 1.0f)
                {
                    if (_loopBlendDuration > 0f)
                    {
                        _animator.CrossFade(stateInfo.shortNameHash, _loopBlendDuration, 0, 0f);
                    }
                    else
                    {
                        _animator.Play(stateInfo.shortNameHash, 0, 0f);
                    }

                    // Restart voice audio in sync with the animation loop
                    RestartAudio();
                }
            }
        }

        private void OnDestroy()
        {
            if (_handInstance != null)
                Destroy(_handInstance);

            if (_audioSource != null)
                Destroy(_audioSource);
        }

        private void RestartAudio()
        {
            if (_audioSource != null && _audioSource.clip != null)
            {
                if (_audioOffset > 0f)
                {
                    _audioSource.Stop();
                    _audioSource.PlayDelayed(_audioOffset);
                }
                else if (_audioOffset < 0f)
                {
                    _audioSource.time = -_audioOffset;
                    _audioSource.Play();
                }
                else
                {
                    _audioSource.time = 0f;
                    _audioSource.Play();
                }
            }
        }

        // ─── Setup ─────────────────────────────────────────────────────

        private void SetupHand()
        {
            // ── Instantiate INACTIVE so Awake/Start don't fire on tracking components ──
            // This prevents HandVisual.Start() from asserting about missing IHand.
            bool prefabWasActive = _handPrefab.activeSelf;
            _handPrefab.SetActive(false);

            _handInstance = Instantiate(_handPrefab, transform);

            _handPrefab.SetActive(prefabWasActive); // restore prefab state

            _handInstance.name = _handPrefab.name + "_Playback";
            _handInstance.transform.localPosition = Vector3.zero;
            _handInstance.transform.localRotation = Quaternion.identity;

            // ── Disable tracking components BEFORE activating ──────────────
            // XR Hands components
            DisableComponentByName(_handInstance, "XRHandSkeletonDriver");
            DisableComponentByName(_handInstance, "XRHandTrackingEvents");
            DisableComponentByName(_handInstance, "XRHandMeshController");

            // Meta Interaction SDK components
            DisableInteractionSDKComponents(_handInstance);

            // ── NOW activate — only the Animator and SkinnedMeshRenderer run ──
            _handInstance.SetActive(true);

            // Ensure the SkinnedMeshRenderer is visible
            var smr = _handInstance.GetComponentInChildren<SkinnedMeshRenderer>(true);
            if (smr != null)
            {
                smr.enabled = true;

                // Apply material override if set
                if (_handMaterial != null)
                    smr.sharedMaterial = _handMaterial;

                Debug.Log($"[HandAnimationPlayer] Mesh renderer enabled on \"{smr.gameObject.name}\".");
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] No SkinnedMeshRenderer found on hand prefab!");
            }

            // ── Determine the animation root ─────────────────────────────────
            // The Meta recorder (HandAnimationRecorder / DualHandAnimationRecorder)
            // writes curve paths relative to HandVisual.Root. Crucially,
            // HandVisual.Root is the PARENT of the wrist bone, not the wrist
            // itself. So recorded paths look like:
            //   path ""                              → HandVisual.Root (parent of wrist)
            //   path "XRHand_Wrist"                  → the wrist bone
            //   path "XRHand_Wrist/XRHand_Palm"      → palm under wrist
            //   path "XRHand_Wrist/XRHand_ThumbMeta…" → finger bones
            //
            // SkinnedMeshRenderer.rootBone points to XRHand_Wrist (the wrist
            // bone itself), so we go one level UP to its parent to match
            // HandVisual.Root. The Animator must sit there for all curve
            // paths to resolve correctly.
            Transform animRoot = _handInstance.transform;
            if (smr != null && smr.rootBone != null)
            {
                // smr.rootBone = XRHand_Wrist; we need its parent = HandVisual.Root
                if (smr.rootBone.parent != null)
                {
                    animRoot = smr.rootBone.parent;
                    Debug.Log($"[HandAnimationPlayer] Animation root: \"{animRoot.name}\" " +
                              $"(parent of rootBone \"{smr.rootBone.name}\")");
                }
                else
                {
                    animRoot = smr.rootBone;
                    Debug.LogWarning($"[HandAnimationPlayer] rootBone \"{smr.rootBone.name}\" has no parent — " +
                                     "using it directly. Finger curves may not resolve.");
                }
            }
            else
            {
                Debug.LogWarning("[HandAnimationPlayer] No rootBone found — Animator will be on the prefab root. " +
                                 "Finger curves may not resolve if they were recorded relative to a child bone.");
            }

            // Add Animator on the animation root (not the prefab root)
            _animator = animRoot.GetComponent<Animator>();
            if (_animator == null)
                _animator = animRoot.gameObject.AddComponent<Animator>();

            _animator.runtimeAnimatorController = _animatorController;

            // applyRootMotion = false ensures root position/rotation curves
            // (path "") are applied as regular property animations — absolute
            // local-position values from the clip, NOT accumulated deltas.
            // This preserves the world-space positions recorded during capture,
            // so both hands maintain correct relative positioning.
            _animator.applyRootMotion = false;

            // Snap to frame 0 pose, then pause until start delay elapses
            _animator.Update(0f);
            _animator.speed = 0f;

            // ── Voice audio ──────────────────────────────────────────────────
            if (_voiceClip != null)
            {
                _audioSource = gameObject.AddComponent<AudioSource>();
                _audioSource.clip = _voiceClip;
                _audioSource.volume = _voiceVolume;
                _audioSource.loop = false;       // we handle loop-sync manually
                _audioSource.playOnAwake = false;
                _audioSource.spatialBlend = 0f;  // 2D audio (non-spatial)

                // Bypass Meta XR Audio spatial processing which attenuates volume
                _audioSource.bypassEffects = true;
                _audioSource.bypassListenerEffects = true;
                _audioSource.bypassReverbZones = true;

                // Remove MetaXRAudioSource if Meta's plugin auto-added it
                DisableComponentByName(gameObject, "MetaXRAudioSource");
            }

            // Both animation and audio wait for _startDelay before playing
            _playbackStartPending = true;
            _pendingStartTime = Time.time;

            Debug.Log($"[HandAnimationPlayer] Playback ready: {_handInstance.name} with {_animatorController.name} " +
                      $"(loop={_loop}, animRoot={animRoot.name}, startDelay={_startDelay}s)");
        }

        // ─── Helpers ────────────────────────────────────────────────────

        /// <summary>
        /// Finds and disables a MonoBehaviour by type name on the given GameObject
        /// or any of its children. Same pattern as HandMeshVisualizer.
        /// </summary>
        private static void DisableComponentByName(GameObject root, string typeName)
        {
            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp != null && comp.GetType().Name == typeName)
                {
                    comp.enabled = false;
                    Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                    return;
                }
            }
        }

        /// <summary>
        /// Also disable Meta Interaction SDK components for OVR hand prefabs.
        /// </summary>
        private static void DisableInteractionSDKComponents(GameObject root)
        {
            string[] componentNames = {
                "HandVisual",
                "HandPuppet",
                "FromOVRHandDataSource",
                "Hand",
                "SyntheticHand",
                "LastKnownGoodHand",
                "FixedScaleHand"
            };

            foreach (var comp in root.GetComponentsInChildren<MonoBehaviour>(true))
            {
                if (comp == null) continue;
                string typeName = comp.GetType().Name;
                foreach (var name in componentNames)
                {
                    if (typeName == name)
                    {
                        comp.enabled = false;
                        Debug.Log($"[HandAnimationPlayer] Disabled {typeName} on \"{comp.gameObject.name}\".");
                        break;
                    }
                }
            }
        }
    }
}
